---
kind: pipeline
type: docker
name: default

steps:
- name: directip
  image: registry.gitlab.com/ulrichschreiner/go-web-dev:latest
  commands:
  - make test build
  - echo "latest,g$(git rev-parse --short=8 HEAD)" >.tags

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: quay.io/protegear/directip
    username:
      from_secret: quay_username
    password:
      from_secret: quay_password

