---
kind: pipeline
type: docker
name: default

steps:
- name: directip
  image: ulrichschreiner/go-web-dev:latest
  commands:
  - make test build
  - echo "g$(git rev-parse --short=8 HEAD)" >.tags

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: protegear/directip
    username:
      from_secret: hub_username
    password:
      from_secret: hub_password

